import sys
import os

# web/pyscripts/backend.py -> repo root (two levels up), so `import groups`
# finds the top-level `groups` package regardless of the process cwd or OS.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _REPO_ROOT not in sys.path:
    sys.path.append(_REPO_ROOT)
import groups as gp


def _find_generators(group, H):
    H_set = frozenset(H)
    if len(H_set) <= 1:
        return [next(iter(H_set))]
    
    # Check if cyclic first (generated by a single element)
    for h in H:
        if group._generate({h}) == H_set:
            return [h]
            
    # If not cyclic, find minimal subset of size 2, 3 etc.
    import itertools
    for r in range(2, len(H_set) + 1):
        for combo in itertools.combinations(H_set, r):
            if group._generate(combo) == H_set:
                return list(combo)
    return list(H_set)

def _subgroup_data(group):
    """
    Subgroup structure for display in the info panel, and for the table/
    graph subgroup-highlighting UI. Full lattice when the group is small
    enough to compute it quickly; otherwise just the cheap cyclic
    subgroups, with a flag so the template can explain why.
    """
    subs = group.subgroups()
    capped = subs is None
    if capped:
        subs = group.cyclic_subgroups()

    subgroup_info = []
    for H in subs:
        sub_gens = _find_generators(group, H)
        subgroup_info.append({
            'elements': sorted(h.__str__() for h in H),
            'order': len(H),
            'normal': group.is_normal(H),
            'cosets': [sorted(e.__str__() for e in c) for c in group.cosets(H, side='left')],
            'generators': sorted(g.__str__() for g in sub_gens),
        })

    covers = None
    if not capped:
        lattice = group.subgroup_lattice()
        if lattice:
            covers = lattice['covers']

    return {
        'subgroups': subgroup_info,
        'subgroups_capped': capped,
        'covers': covers,
    }



def create(choice,*,character=None,size=None,gen=None):
    if gen is None:
        gen = []
    match choice:
        case 'Z':
            if character == '+':
                group = gp.MnA(size,generators=gen)
            else:
                group = gp.MnM(size,generators=gen)
            return {
                'inverses': group._inverses,
                'elements': group._elements,
                'cayleys': group.cayleys(),
                'vertices': group.vertices,
                'edges': group.edges,
                'choices': group.__str__(),
                'gen':group.generators,
                'conjugacy_classes':group.conjugacy_classes(),
                **_subgroup_data(group),
            }
        case 'P':
            if character == 'S_n':
                group = gp.Sn(size,
                              0,
                              gen)
            else:
                group = gp.Sn(size,
                               1,
                               gen)         
            return {
                'inverses' : group._inverses,
                'elements': group._elements,
                'cayleys': group.cayleys(),
                'vertices': group.vertices,
                'edges':group.edges,
                'choices':group.__str__(),
                'gen':group._generators,
                'conjugacy_classes':group.conjugacy_classes(),
                **_subgroup_data(group),
            }
        case 'D':
            group = gp.Dn(2*size,
                          generators=gen)
            return {
                'inverses': group._inverses,
                'elements': group._elements,
                'cayleys': group.cayleys(),
                'gen': [i.__str__() for i in group._generators],
                'vertices': group.vertices,
                'edges':group.edges,
                'choices':group.__str__(),
                'conjugacy_classes':group.conjugacy_classes(),
                **_subgroup_data(group),
            } 
        case 'Product':
            subgroups = []
            for g_type, size, op in character:
                if g_type == 'Z':
                    if op == '+':
                        g = gp.MnA(size)
                    else:
                        g = gp.MnM(size)
                elif g_type == 'D':
                    g = gp.Dn(2 * size)
                elif g_type == 'S':
                    if op == 'S_n':
                        g = gp.Sn(size, 0)
                    else:
                        g = gp.Sn(size, 1)
                else:
                    g = None
                if g:
                    subgroups.append(g)

            group = gp.Pn(subgroups, generators=gen)
            
            from .colors import choose
            colors = [choose() for _ in range(group._order)]
            for i, c in zip(group._elements, colors):
                i.color = c

            return {
                'inverses': group._inverses,
                'elements': group._elements,
                'cayleys': group.cayleys(),
                'vertices': group.vertices,
                'edges': group.edges,
                'choices': group.__str__(),
                'gen': group.generators,
                'conjugacy_classes': group.conjugacy_classes(),
                **_subgroup_data(group),
            }