from re import L


class element:
    def __init__(self
                 )->None:
        self.order = None

    def __mul__(self,
                other
                ):
        raise NotImplementedError
    
    def __matmul__(self,
                 other
                 ):
        raise NotImplementedError

    def __pow__(self,
                n):
        temp = self
        for i in range(n-1):
            temp*= self
        return temp

    def __eq__(self, value):
        """
        Naive as of now
        """
        if isinstance(value, element):
            try:
                return self._number == value._number
            except AttributeError:
                return self._string == value._string
        return False

    def __hash__(self):
        try:
            return hash(self._number)
        except AttributeError:
            return hash(self._string)

    def __int__(self):
        return self._number
    
    def __str__(self):
        return str(self._number)
    

class Group:
    def __init__(self,
                 order,
                 **kwargs) -> None:
        self._identity = None
    
    def elements(self
                 ):
        return self._elements
    
    def cayleys(self
               ):
        return [[i*j for j in self._elements] for i in self._elements]
     
    def generators(self
                    ):
        self._generators = [i for i in self._elements if i._order == self._order]
    
    def cycles(self,
               j):
        if isinstance(j, element):
            return [i*j for i in self._elements]
        else:
            raise TypeError("Input must be an instance of the element class.")


    def update_graph(self,
                    generators = []):
        raise NotImplementedError

    def conjugacy_classes(self
                          ):
        elements = set(self._elements)
        classes = []
        while elements:
            temp = self.conjugates(elements.pop())
            classes.append(temp)
            elements = elements - temp
        return classes
    

    def conjugates(self,
                   L):
        """
        Conjugacy is expanding to the minimum class of elements where they behave commutatively.
        So, if ab != ba = ca. The question is what are the possibilities of c for a given b, which means aba^-1.
        """
        G = set()
        try:
            len(L)
            L = list(L)
            for i in self._elements:
                for j in L:
                    G.add(i*j*self._inverses[i])
            return G
        except TypeError:
            # L has no len(), so it's a single element rather than an iterable
            for i in self._elements:
                G.add(i*L*self._inverses[i])
            return G

    def _generate(self,
                  subset):
        """
        The subgroup generated by `subset`: repeatedly close under
        multiplication until nothing new appears. Since every element in a
        finite group has finite order, an element's inverse is just one of
        its own powers (a^(order-1)), so this power-closure already yields a
        genuine subgroup without needing to add inverses separately.
        """
        subset = frozenset(subset)
        cache = self.__dict__.setdefault('_generate_cache', {})
        if subset in cache:
            return cache[subset]

        current = set(subset)
        changed = True
        while changed:
            changed = False
            products = {a * b for a in current for b in current}
            if not products <= current:
                current |= products
                changed = True

        result = frozenset(current)
        cache[subset] = result
        return result

    # Full lattice enumeration is fast for everything this app actually
    # constructs (mod-n up to 30, D_n up to order 30, S_n/A_n up to n=4,
    # i.e. order 24) but S_5/A_5 (order 120/60) take 20-30+ seconds with this
    # pure-Python closure approach - too slow for a single web request on a
    # single-threaded dev server. Above this order, subgroups() bails out to
    # None and callers should fall back to cyclic_subgroups() instead.
    _MAX_ORDER_FOR_FULL_SUBGROUP_LATTICE = 32

    def cyclic_subgroups(self
                         ):
        """
        The cyclic subgroup <g> generated by each single element g. Cheap to
        compute (each is just the powers of one element) even for groups
        where the full subgroup lattice is too expensive to enumerate.
        """
        found = []
        for g in self._elements:
            H = self._generate({g})
            if H not in found:
                found.append(H)
        return sorted(found, key=len)

    def subgroups(self
                  ):
        """
        Enumerate every subgroup of the group.

        Every subgroup H is the union of the cyclic subgroups generated by
        each of its own elements (h is always in <h>, so that union already
        contains all of H, and is contained in H since H is closed). So:
        start from all cyclic subgroups (the "atoms"), then repeatedly join
        pairs of already-found subgroups (generate the subgroup generated by
        their union) until no new subgroup appears. This fixed point is
        exactly the full subgroup lattice.

        Uses a worklist so each newly-found subgroup is only ever joined
        against the subgroups known *at that point*, rather than re-scanning
        every pair on every pass - the naive full-rescan version is
        intractable once the group has more than ~30-40 elements (e.g. S5).

        Returns None if the group is larger than
        _MAX_ORDER_FOR_FULL_SUBGROUP_LATTICE - callers should fall back to
        cyclic_subgroups() in that case.
        """
        if len(self._elements) > self._MAX_ORDER_FOR_FULL_SUBGROUP_LATTICE:
            return None

        found = list(self.cyclic_subgroups())

        def add_if_new(H):
            if H in found:
                return None
            found.append(H)
            return len(found) - 1

        frontier = list(range(len(found)))
        while frontier:
            next_frontier = []
            for idx in frontier:
                H = found[idx]
                # snapshot: found may grow while we iterate over it
                for K in found[:]:
                    new_idx = add_if_new(self._generate(H | K))
                    if new_idx is not None:
                        next_frontier.append(new_idx)
            frontier = next_frontier

        return sorted(found, key=len)

    def subgroup_lattice(self
                         ):
        """
        Covering relations for the subgroup lattice's Hasse diagram: for each
        subgroup, which other (strictly smaller) subgroups it directly
        covers, i.e. with no subgroup strictly in between.

        Returns None if subgroups() did (group too large - see
        _MAX_ORDER_FOR_FULL_SUBGROUP_LATTICE).
        """
        subs = self.subgroups()
        if subs is None:
            return None
        covers = {i: [] for i in range(len(subs))}
        for i, H in enumerate(subs):
            for j, K in enumerate(subs):
                if K < H:
                    if not any(K < subs[k] < H for k in range(len(subs))):
                        covers[i].append(j)
        return {'subgroups': subs, 'covers': covers}


        return len(self._order)
    
    def __getitem__(self, key):
        if isinstance(key, int):
            return self._elements[key]
        elif isinstance(key, str):
            return next((i for i in self._elements if i.__str__() == key), None)
        else:
            raise TypeError("Key must be an integer or a string representing the element.")

    def __iter__(self):
        return iter(self._elements)

    def __str__(self) -> list:
        return [i.__str__() for i in self._elements]